# Springboard Data Science Career Track Unit 4 Challenge - Tier 3 Complete

## Objectives
Hey! Great job getting through those challenging DataCamp courses. You're learning a lot in a short span of time. 

In this notebook, you're going to apply the skills you've been learning, bridging the gap between the controlled environment of DataCamp and the *slightly* messier work that data scientists do with actual datasets!

Here’s the mystery we’re going to solve: ***which boroughs of London have seen the greatest increase in housing prices, on average, over the last two decades?***


A borough is just a fancy word for district. You may be familiar with the five boroughs of New York… well, there are 32 boroughs within Greater London [(here's some info for the curious)](https://en.wikipedia.org/wiki/London_boroughs). Some of them are more desirable areas to live in, and the data will reflect that with a greater rise in housing prices.

***This is the Tier 3 notebook, which means it's not filled in at all: we'll just give you the skeleton of a project, the brief and the data. It's up to you to play around with it and see what you can find out! Good luck! If you struggle, feel free to look at easier tiers for help; but try to dip in and out of them, as the more independent work you do, the better it is for your learning!***

This challenge will make use of only what you learned in the following DataCamp courses: 
- Prework courses (Introduction to Python for Data Science, Intermediate Python for Data Science)
- Data Types for Data Science
- Python Data Science Toolbox (Part One) 
- pandas Foundations
- Manipulating DataFrames with pandas
- Merging DataFrames with pandas

Of the tools, techniques and concepts in the above DataCamp courses, this challenge should require the application of the following: 
- **pandas**
    - **data ingestion and inspection** (pandas Foundations, Module One) 
    - **exploratory data analysis** (pandas Foundations, Module Two)
    - **tidying and cleaning** (Manipulating DataFrames with pandas, Module Three) 
    - **transforming DataFrames** (Manipulating DataFrames with pandas, Module One)
    - **subsetting DataFrames with lists** (Manipulating DataFrames with pandas, Module One) 
    - **filtering DataFrames** (Manipulating DataFrames with pandas, Module One) 
    - **grouping data** (Manipulating DataFrames with pandas, Module Four) 
    - **melting data** (Manipulating DataFrames with pandas, Module Three) 
    - **advanced indexing** (Manipulating DataFrames with pandas, Module Four) 
- **matplotlib** (Intermediate Python for Data Science, Module One)
- **fundamental data types** (Data Types for Data Science, Module One) 
- **dictionaries** (Intermediate Python for Data Science, Module Two)
- **handling dates and times** (Data Types for Data Science, Module Four)
- **function definition** (Python Data Science Toolbox - Part One, Module One)
- **default arguments, variable length, and scope** (Python Data Science Toolbox - Part One, Module Two) 
- **lambda functions and error handling** (Python Data Science Toolbox - Part One, Module Four)

## The Data Science Pipeline

This is Tier Three, so we'll get you started. But after that, it's all in your hands! When you feel done with your investigations, look back over what you've accomplished, and prepare a quick presentation of your findings for the next mentor meeting. 

Data Science is magical. In this case study, you'll get to apply some complex machine learning algorithms. But as  [David Spiegelhalter](https://www.youtube.com/watch?v=oUs1uvsz0Ok) reminds us, there is no substitute for simply **taking a really, really good look at the data.** Sometimes, this is all we need to answer our question.

Data Science projects generally adhere to the four stages of Data Science Pipeline:
1. Sourcing and loading 
2. Cleaning, transforming, and visualizing 
3. Modeling 
4. Evaluating and concluding

### 1. Sourcing and Loading 

Any Data Science project kicks off by importing  ***pandas***. The documentation of this wonderful library can be found [here](https://pandas.pydata.org/). As you've seen, pandas is conveniently connected to the [Numpy](http://www.numpy.org/) and [Matplotlib](https://matplotlib.org/) libraries. 

***Hint:*** This part of the data science pipeline will test those skills you acquired in the pandas Foundations course, Module One.

#### 1.1. Importing Libraries

In [3]:
# Let's import the pandas, numpy libraries as pd, and np respectively. 
import pandas as pd
import matplotlib.pyplot as plt
import os

# Load the pyplot collection of functions from matplotlib, as plt

#### 1.2.  Loading the data
Your data comes from the [London Datastore](https://data.london.gov.uk/): a free, open-source data-sharing portal for London-oriented datasets.

In [4]:
# First, make a variable called url_LondonHousePrices, and assign it the following link, enclosed in quotation-marks as a string:
# https://data.london.gov.uk/download/uk-house-price-index/70ac0766-8902-4eb5-aab5-01951aaed773/UK%20House%20price%20index.xls

# The dataset we're interested in contains the Average prices of the houses, and is actually on a particular sheet of the Excel file. 
# As a result, we need to specify the sheet name in the read_excel() method.
# Put this data into a variable called properties.  
properties = pd.read_excel('UK House price index.xlsx', 
                           sheet_name='Average price', 
                           index_col=None)

### 2. Cleaning, transforming, and visualizing
This second stage is arguably the most important part of any Data Science project. The first thing to do is take a proper look at the data. Cleaning forms the majority of this stage, and can be done both before or after Transformation.

The end goal of data cleaning is to have tidy data. When data is tidy: 

1. Each variable has a column.
2. Each observation forms a row.

Keep the end goal in mind as you move through this process, every step will take you closer. 



***Hint:*** This part of the data science pipeline should test those skills you acquired in: 
- Intermediate Python for data science, all modules.
- pandas Foundations, all modules. 
- Manipulating DataFrames with pandas, all modules.
- Data Types for Data Science, Module Four.
- Python Data Science Toolbox - Part One, all modules

**2.1. Exploring your data** 

Think about your pandas functions for checking out a dataframe.

In [5]:
properties.head()

,Unnamed: 0,City of London,Barking & Dagenham,Barnet,Bexley,Brent,Bromley,Camden,Croydon,Ealing,...,NORTH WEST,YORKS & THE HUMBER,EAST MIDLANDS,WEST MIDLANDS,EAST OF ENGLAND,LONDON,SOUTH EAST,SOUTH WEST,Unnamed: 47,England
0,NaT,E09000001,E09000002,E09000003,E09000004,E09000005,E09000006,E09000007,E09000008,E09000009,...,E12000002,E12000003,E12000004,E12000005,E12000006,E12000007,E12000008,E12000009,NaN,E92000001
1,1995-01-01,90347,51870,98948,64956,76880,83082,119775,70118,85469,...,40907,42171,43856,46470,56098,79687,64502,52799,NaN,50231
2,1995-02-01,81213,52513,98848,64786,77651,83068,118365,69908,86551,...,40877,41912,44344,47249,55991,77913,64196,52462,NaN,50130
3,1995-03-01,78168,52701,97848,64366,77644,82856,119131,69666,87067,...,41351,42544,43701,47345,55574,79110,64597,51716,NaN,50229
4,1995-04-01,76172,54618,96273,64276,78668,82525,118948,69562,87933,...,41195,42934,44414,47359,55966,79708,65111,52877,NaN,50597

**2.2. Cleaning the data**

You might find you need to transpose your dataframe, check out what its row indexes are, and reset the index. You  also might find you need to assign the values of the first row to your column headings  . (Hint: recall the .columns feature of DataFrames, as well as the iloc[] method).

Don't be afraid to use StackOverflow for help  with this.

In [6]:
#Make borughs on side by transposing
properties_t = properties.transpose()
properties_t.head()
properties_t = properties_t.reset_index()
#make first row the columns
properties_t.columns = properties_t.iloc[0]
properties_t.head()

,Unnamed: 0,NaT,1995-01-01 00:00:00,1995-02-01 00:00:00,1995-03-01 00:00:00,1995-04-01 00:00:00,1995-05-01 00:00:00,1995-06-01 00:00:00,1995-07-01 00:00:00,1995-08-01 00:00:00,...,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00,2026-04-01 00:00:00,2026-05-01 00:00:00
0,Unnamed: 0,NaT,1995-01-01 00:00:00,1995-02-01 00:00:00,1995-03-01 00:00:00,1995-04-01 00:00:00,1995-05-01 00:00:00,1995-06-01 00:00:00,1995-07-01 00:00:00,1995-08-01 00:00:00,...,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00,2026-04-01 00:00:00,2026-05-01 00:00:00
1,City of London,E09000001,90347,81213,78168,76172,83392,93757,108801,110976,...,852425,765344,731418,709478,762272,732377,691441,604656,612427,626980
2,Barking & Dagenham,E09000002,51870,52513,52701,54618,54524,55200,53569,53691,...,354988,357277,359638,361107,357921,358499,361952,360125,360007,360889
3,Barnet,E09000003,98948,98848,97848,96273,95737,95577,96992,97968,...,623157,614607,597772,595567,590558,585156,585233,587001,587297,590583
4,Bexley,E09000004,64956,64786,64366,64276,63995,64251,63721,64431,...,407407,410713,413619,416894,413487,411474,404957,408880,408488,408585

**2.3. Cleaning the data (part 2)**

You might we have to **rename** a couple columns. How do you do this? The clue's pretty bold...

In [7]:
#drop old first row
properties_t = properties_t.drop(0)
properties_t = properties_t.rename(columns={ pd.NaT:'ID', 'Unnamed: 0':'Boroughs'})
properties_t.head()

,Boroughs,ID,1995-01-01 00:00:00,1995-02-01 00:00:00,1995-03-01 00:00:00,1995-04-01 00:00:00,1995-05-01 00:00:00,1995-06-01 00:00:00,1995-07-01 00:00:00,1995-08-01 00:00:00,...,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00,2026-04-01 00:00:00,2026-05-01 00:00:00
1,City of London,E09000001,90347,81213,78168,76172,83392,93757,108801,110976,...,852425,765344,731418,709478,762272,732377,691441,604656,612427,626980
2,Barking & Dagenham,E09000002,51870,52513,52701,54618,54524,55200,53569,53691,...,354988,357277,359638,361107,357921,358499,361952,360125,360007,360889
3,Barnet,E09000003,98948,98848,97848,96273,95737,95577,96992,97968,...,623157,614607,597772,595567,590558,585156,585233,587001,587297,590583
4,Bexley,E09000004,64956,64786,64366,64276,63995,64251,63721,64431,...,407407,410713,413619,416894,413487,411474,404957,408880,408488,408585
5,Brent,E09000005,76880,77651,77644,78668,79464,80118,79920,79295,...,555794,556967,557828,567067,568445,553470,537567,543165,547995,548895

**2.4.Transforming the data**

Remember what Wes McKinney said about tidy data? 

You might need to **melt** your DataFrame here.

In [8]:
#melt to make vertical data
clean_prop = properties_t.melt(id_vars=['Boroughs','ID'],var_name= 'year',value_name='price')
clean_prop = clean_prop.drop(0)
clean_prop.head()

             Boroughs         ID                 year  price
1  Barking & Dagenham  E09000002  1995-01-01 00:00:00  51870
2              Barnet  E09000003  1995-01-01 00:00:00  98948
3              Bexley  E09000004  1995-01-01 00:00:00  64956
4               Brent  E09000005  1995-01-01 00:00:00  76880
5             Bromley  E09000006  1995-01-01 00:00:00  83082

Remember to make sure your column data types are all correct. Average prices, for example, should be floating point numbers...

In [12]:
#change data type back to original
clean_prop.dtypes
clean_prop['year'] = pd.to_datetime(clean_prop['year'])
clean_prop['price'] = pd.to_numeric(clean_prop['price'], errors='coerce')
clean_prop.dtypes

Boroughs            object
ID                  object
year        datetime64[ns]
price              float64
dtype: object

**2.5. Cleaning the data (part 3)**

Do we have an equal number of observations in the ID, Average Price, Month, and London Borough columns? Remember that there are only 32 London Boroughs. How many entries do you have in that column? 

Check out the contents of the London Borough column, and if you find null values, get rid of them however you see fit.

In [13]:
#Inspecting invalid data
clean_prop.isna().any()
clean_prop.isnull().sum()
clean_prop[clean_prop.isnull().any(axis=1)]
clean_prop.count()
clean_prop['Boroughs'].nunique()

48

In [22]:
#setting borough as index for dropping rows
clean_prop = clean_prop.set_index('Boroughs')
clean_prop = clean_prop.drop(['Unnamed: 37', 'Unnamed: 47', 'Unnamed: 34'])

In [23]:
#reset index
clean_prop = clean_prop.reset_index()
clean_prop.head()

             Boroughs         ID       year    price
0  Barking & Dagenham  E09000002 1995-01-01  51870.0
1              Barnet  E09000003 1995-01-01  98948.0
2              Bexley  E09000004 1995-01-01  64956.0
3               Brent  E09000005 1995-01-01  76880.0
4             Bromley  E09000006 1995-01-01  83082.0

In [25]:
#check which aernt boroughs
clean_prop[['Boroughs', 'ID']].drop_duplicates()
#drop rows that dont start with E09
full_clean_prop = clean_prop[clean_prop['ID'].str.startswith('E09')]
len(full_clean_prop['Boroughs'].unique())

             Boroughs         ID       year    price
0  Barking & Dagenham  E09000002 1995-01-01  51870.0
1              Barnet  E09000003 1995-01-01  98948.0
2              Bexley  E09000004 1995-01-01  64956.0
3               Brent  E09000005 1995-01-01  76880.0
4             Bromley  E09000006 1995-01-01  83082.0

**2.6. Visualizing the data**

To visualize the data, why not subset on a particular London Borough? Maybe do a line plot of Month against Average Price?

In [ ]:
#assumed this was optional

To limit the number of data points you have, you might want to extract the year from every month value your *Month* column. 

To this end, you *could* apply a ***lambda function***. Your logic could work as follows:
1. look through the `Month` column
2. extract the year from each individual value in that column 
3. store that corresponding year as separate column. 

Whether you go ahead with this is up to you. Just so long as you answer our initial brief: which boroughs of London have seen the greatest house price increase, on average, over the past two decades?

In [ ]:
#assumed this was optional

**3. Modeling**

Consider creating a function that will calculate a ratio of house prices, comparing the price of a house in 2018 to the price in 1998.

Consider calling this function create_price_ratio.

You'd want this function to:
1. Take a filter of dfg, specifically where this filter constrains the London_Borough, as an argument. For example, one admissible argument should be: dfg[dfg['London_Borough']=='Camden'].
2. Get the Average Price for that Borough, for the years 1998 and 2018.
4. Calculate the ratio of the Average Price for 1998 divided by the Average Price for 2018.
5. Return that ratio.

Once you've written this function, you ultimately want to use it to iterate through all the unique London_Boroughs and work out the ratio capturing the difference of house prices between 1998 and 2018.

Bear in mind: you don't have to write a function like this if you don't want to. If you can solve the brief otherwise, then great! 

***Hint***: This section should test the skills you acquired in:
- Python Data Science Toolbox - Part One, all modules

In [6]:
#Get the last price for the boroughs
last_price = full_clean_prop.groupby('Boroughs')['price'].last()
#Get the price from may 2006(its 20 years ago)(have to set index so it can match lastprice)
price_2006 = full_clean_prop[full_clean_prop['year'] == '2006-05-01'].set_index('Boroughs')['price']
price_2006.head()
#The difference between both of them
price_diff = last_price - price_2006
#put in descending order to see which had greatest increase
price_diff= price_diff.sort_values(ascending=False)
#print(price_diff)
print(price_diff)

NameError: name 'full_clean_prop' is not defined

In [5]:
# find the increase of each borough
decade_increase = last_price / price_2006
decade_increase = decade_increase.sort_values(ascending=False)
print(decade_increase)

NameError: name 'last_price' is not defined

### 4. Conclusion
What can you conclude? Type out your conclusion below. 

Look back at your notebook. Think about how you might summarize what you have done, and prepare a quick presentation on it to your mentor at your next meeting. 

We hope you enjoyed this practical project. It should have consolidated your data hygiene and pandas skills by looking at a real-world problem involving just the kind of dataset you might encounter as a budding data scientist. Congratulations, and looking forward to seeing you at the next step in the course!

In [ ]:
#In conclusion, Waltham Forest has had the greatest average increase in housing prices over the past two decades.

In [3]:
#Visualization for meeting
data_plot = decade_increase.plot(kind='bar',title='Housing Price Increase by London Borough (2006-2026)', figsize=(12, 6),xlabel='Borough', ylabel='Price Increase', rot=90)

NameError: name 'decade_increase' is not defined

In [1]:
plt.savefig('my_plot.png')   # PNG image

NameError: name 'plt' is not defined